when:
  - event: tag
    ref: refs/tags/v*

steps:
  release_docker_image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
      API_SERVER_HOST:
        from_secret: API_SERVER_HOST
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - docker pull suilteam/cxyfs:alpine-latest
      - >-
        docker build --build-arg CXY_LANG_PLAYGROUND_API_SERVER=$API_SERVER_HOST
        -t suilteam/cxy-playground-ui:latest -t suilteam/cxy-playground-ui:${CI_COMMIT_TAG}
        -f Dockerfile .
      - docker push suilteam/cxy-playground-ui:latest
      - docker push suilteam/cxy-playground-ui:${CI_COMMIT_TAG}
